### ISSUE TITLE
Permisions not working

### ISSUE THREAD

**Issue by TheChampTF** [troed/Courier#11]
It says on your page that default is set to OP, but yet all can use it.

Also I sent you a pm and missing a respond on that.

**Comment by cwc** [comment]
@TheChampTF which permissions specifically have this problem?

**Comment by ghost** [comment]
Problem is all can use the commands, not limited to OP's as the default setting is.

**Comment by cwc** [comment]
Hm, just to be sure, do you have a permissions mod such as bPermissions that's configured? If so, which one? It seems to be working for me with bPermissions.

**Comment by ghost** [comment]
I'm using permison ex and yes it's set up

**Comment by cwc** [comment]
I tested this for a bit, and I'm afraid I wasn't able to replicate the problem with my bPermissions setup. I did encounter something else weird, though.

If I edited the permissions files and tried to reload them while the server was running (with `/permissions reload`), the new permissions _did not_ take effect. This briefly led to the same symptoms you described. However, after restarting the server, the permissions worked as expected. I tried this a few times, and I consistently had to restart in order to apply new permissions.

I'm not sure if my perms plugin isn't reloaded correctly, or if it's a bug in the server's perms implementation (I use the latest Spigot build). Perhaps try restarting your server, and seeing if the new perms have applied? If that doesn't fix it, I'm out of ideas.
