### ISSUE TITLE
NPE when sending to player

### ISSUE THREAD

**Issue by cwc** [troed/Courier#8]
[Location of NPE](https://github.com/troed/Courier/blob/master/src/se/troed/plugin/Courier/CourierCommands.java#L174)

Just installed the latest release and tried to /post to myself as well as to another player. Server log shows a NullPointerException, presumably on `o.getName()` as the API says it can return null in some cases.

**Comment by troed** [comment]
Thanks. The v1.8 compatibility came through a pull request and this did not show up in any testing. I do not know what is different between servers where it happens and others.

Bug tracker with what seems to be the same problem: http://dev.bukkit.org/bukkit-plugins/courier/tickets/110-internal-error-post/

**Comment by cwc** [comment]
Cool, I should have mentioned that I'm using Spigot 1.8.3 also. I've actually pulled down the code and gotten it building with Gradle, maybe I can poke around and find something.

**Comment by cwc** [comment]
Do you think it's acceptable to just `continue` if the name is null in that loop? From what I can tell, if the list of offline players from the API doesn't include a player with a matching name, the plugin is SOL on sending it and just has to wait until they come online.

**Comment by troed** [comment]
Yeah adding a check to make sure getName() isn't null should work. Depending on why the server returns null entries I guess it might confuse users not being able to send to someone.

**Comment by cwc** [comment]
Maybe change the message to something like `Couldn't deliver to PlayerName, try again when they're online.`?

Also, are you interested in a PR with a Gradle setup? Biggest difference is moving the source into `src/main/java`, though that's just for convention. Having the Gradle wrapper is quite nice for building on a headless server.

**Comment by troed** [comment]
Well, I would only change if it's actually the case that null can be returned for a player that exists on the server. If it is, and it only happens on Spigot and not Bukkit, the bug should really be fixed there and Courier can just have a workaround to make sure it doesn't crash. Since I don't play myself at all anymore it's not something I will dig deep into.

I will accept mostly all pull requests that look sane and I believe will make it easier for others to work on Courier :)
